import './globals.css'
import { Inter } from 'next/font/google'

import Navbar from "@components/Navbar";
import Provider from "@components/Provider";
import styles from '@styles/style';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body  className={`bg-primary w-full overflow-x-hidden ${inter.className}`} id='main-div'>
        <Provider>
          <main >
            <div  >
              <div className={`${styles.paddingX} ${styles.flexStart}`}>
                <div className={`${styles.boxWidth}`}>
                  <Navbar />
                </div>
                 {/* gradient start */}
          <div className="absolute z-[0] w-[40%] h-[30%] top-0 pink__gradient" />
          <div className="absolute z-[1] w-[80%] h-[39%] rounded-full white__gradient bottom-40" />
          <div className="absolute z-[0] w-[50%] h-[40%] right-20 bottom-20 blue__gradient" /> 
          {/* gradient end */}
              </div>
            </div>
            {children}
          </main>
        </Provider>
      </body>
    </html>
  )
}
